version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

conda:
  environment: environment.yaml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false


# This part is necessary otherwise the project is not built
python:
  install:
  - method: pip
    path: .[dev,doc]
