# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-phix-dev
#
name: cherab-phix-dev
channels:
- conda-forge
- default
dependencies:
- python = 3.9  # raysect has no built dist for 3.10+
- setuptools
- numpy
- scipy
# - cython == 3.0.0a11 installed by pip temporarily
- matplotlib < 3.6  # for raysect dependency
- plotly
- numpy-stl
- contourpy
  # for developper tools
- black
- isort
- flake8
- mypy
- rich-click
- pre-commit
  # for documentation
- docutils >= 0.19, < 0.20
- ipykernel
- ipywidgets
- nbsphinx
- pillow
- pygments >= 2.11.0
- sphinx >= 5, < 6
- sphinx-prompt
- sphinx-copybutton
- pydata-sphinx-theme < 0.11  # for custom css dependency
- sphinx-design
- pandoc
- sphinx-codeautolink
# pip-install dependencies
- pip
- pip:
  - cython == 3.0.0a11
  - cherab == 1.4.0
  - calcam
  - cython-lint
