# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-phix-dev
#
name: cherab-phix-dev
channels:
- conda-forge
- calcam
dependencies:
- python = 3.10  # cherab has no built dist for 3.11+
- numpy
- meson-python >= 0.15
- cython >= 3.0
- tomli  # python_version < '3.11'
- scipy
- matplotlib < 3.6  # for raysect v0.7.1 dependency (which is dependency of cherab 1.4.0)
- contourpy
- plotly
  # for developper tools
- ipython
- black
- ruff
- mypy
- rich-click
- cython-lint
- pre-commit
- pytest
- setuptools  # for installing with setuptools' editable mode
  # for documentation
- docutils
- ipykernel
- ipywidgets
- jinja2 < 3.1
- nbconvert > 7.3
- nbsphinx
- pandoc
- pillow
- pydata-sphinx-theme < 0.15  # for custom css dependency
- pygments >= 2.11.0
- sphinx >= 7.0, < 8.0
- sphinx-codeautolink
- sphinx-copybutton
- sphinx-design
- sphinx-prompt
# pip-install dependencies
- pip
- pip:
  - cherab == 1.4.0
  - calcam
  - sphinx-github-style
