# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-phix-dev
#
name: cherab-phix-dev2
channels:
- conda-forge
dependencies:
- python ==3.8 #< 3.10
- setuptools
- numpy
- scipy
# - cython == 3.0.0a11 installed by pip temporarily
- matplotlib
- plotly
  # for developper tools
- black
- isort
- flake8
- mypy
- rich-click
- pre-commit
  # for documentation
- docutils >= 0.19, < 0.20
- ipykernel
- ipywidgets
- nbsphinx
- pillow
- pygments >= 2.11.0
- sphinx >= 5, < 6
- sphinx-prompt
- sphinx-copybutton
- pydata-sphinx-theme < 0.11
- numpy-stl
- sphinx-design
- pandoc
- sphinx-codeautolink
# pip-install dependencies
- pip
- pip:
  - cython == 3.0.0a11
  - raysect == 0.7.1
  - cherab == 1.3.0
  - calcam
  - cython-lint
