# To use:
#   $ conda env create -f environment.yaml  # `mamba` works too for this command
#   $ conda activate cherab-phix-dev
#
name: cherab-phix-dev
channels:
- conda-forge
- default
dependencies:
- python = 3.9  # raysect has no built dist for 3.10+
- setuptools
- numpy
- scipy
- cython >= 3.0
- matplotlib < 3.6  # for raysect v0.7.1 dependency (which is dependency of cherab 1.4.0)
- plotly
- numpy-stl
- contourpy
  # for developper tools
- black
- ruff
- mypy
- rich-click
- pre-commit
- cython-lint
  # for documentation
- docutils
- ipython
- ipykernel
- ipywidgets
- nbconvert > 7.3
- nbsphinx
- pillow
- pygments >= 2.11.0
- sphinx >= 5
- sphinx-prompt
- sphinx-copybutton
- pydata-sphinx-theme < 0.14  # for custom css dependency
- sphinx-design
- sphinx-codeautolink
- pandoc
- jinja2 < 3.1
# pip-install dependencies
- pip < 23.1  # compatible with calcam (to avoid pep517 installation)
- pip:
  - cherab == 1.4.0
  - calcam
  - sphinx-github-style
